### ISSUE TITLE
Running gitrisky predict throws error ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by Phillipe-Bojorquez** [hinnefe2/gitrisky#17]
After installing gitrisky and then cd'ing to a repo, I am able to train a repo without any errors.  I see an output that says `Model trained on 5464 training examples with 0 positive cases`

If I then run `gitrisky predict` or `git risky predict -c id` I see the following output:

```Phillipes-MacBook-Pro:lunar phillipeb$ gitrisky predict
Traceback (most recent call last):
  File "/usr/local/bin/gitrisky", line 9, in <module>
    load_entry_point('gitrisky==0.1.2', 'console_scripts', 'gitrisky')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/gitrisky/cli.py", line 67, in predict
    [(_, score)] = model.predict_proba(features)
ValueError: need more than 1 value to unpack
```

**Comment by willmeek** [comment]
Also seeing this
`Model trained on 27 training examples with 0 positive cases`

```$ gitrisky predict
Traceback (most recent call last):
  File "/usr/local/bin/gitrisky", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gitrisky/cli.py", line 67, in predict
    [(_, score)] = model.predict_proba(features)
ValueError: need more than 1 value to unpack
```

**Comment by hinnefe2** [comment]
I'm pretty sure that this is failing because gitrisky wasn't able to find any commits which introduced bugs (per the `0 positive cases` bit in the training output). It identifies bugs by looking for commit messages which contain "BUG" or "FIX", so if none of the commit messages include those words then the model doesn't know what to look for.

The specific error `ValueError: need more than 1 value to unpack` is because `model.predict_proba` is expected to return a tuple of `(not_bug_probability, bug_probability)`, however when the model is trained without any positive examples it just returns `[[1.0]]`.

I'll add some validation to the training step so that you get an informative error message if you try to train a model on a repo without any BUG or FIX commit messages.
