### ISSUE TITLE
App crashes at launch

### ISSUE THREAD

**Issue by nm17** [hinnefe2/gitrisky#6]
Python 2.7.14
```sh
$ gitrisky train
Traceback (most recent call last):
  File "/usr/local/bin/gitrisky", line 11, in <module>
    load_entry_point('gitrisky==0.1.0rc0', 'console_scripts', 'gitrisky')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gitrisky/cli.py", line 29, in train
    model.fit(features, labels.label)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/ensemble/forest.py", line 247, in fit
    X = check_array(X, accept_sparse="csc", dtype=DTYPE)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 433, in check_array
    array = np.array(array, dtype=dtype, order=order, copy=copy)
ValueError: could not convert string to float: MERGE
```

**Comment by hinnefe2** [comment]
Thanks for the bug report!

This should be fixed by 3e10227. The latest version on PyPI has the fix so a fresh `pip install` should work.
